# Generated by Django 4.2.18 on 2025-01-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
