# Generated by Django 4.2.18 on 2025-01-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_category_name_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="authority_from_zarinpal",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
