name: saeid shabani

on:
  push:
    branches: [ "main_one" ]
  pull_request:
    branches: [ "main_one" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: first test
      run: true
